# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18wEjagfXrKr3SW8TwGyiWCc8NRYW2m8H
"""

!pip install groq

import os
os.environ["GROQ_API_KEY"] = "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"
from groq import Groq

client = Groq(api_key=os.environ["GROQ_API_KEY"])

response = client.chat.completions.create(
    model="llama3-8b-8192",  # Replace with "gemini" if Groq hosts it
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Where is TCS head office location located"}
    ]
)

print(response.choices[0].message.content)